import type { Metadata } from "next";
import "./globals.css";
import { FC } from "react";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	weight: ["400", "500", "600", "700", "800"],
	variable: "--font-inter",
	subsets: ["latin"],
});

const RootLayout: FC<
	Readonly<{
		children: React.ReactNode;
	}>
> = ({ children }) => {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>{children}</body>
		</html>
	);
};

export default RootLayout;
